<?php

/**
 * Helper function to apply DemTools DKAN configuration.
 *
 * This function gets called as part of the DKAN install profile by patching in
 * an additional install task.
 */
function demtools_dkan_config() {
  watchdog('demtools_dkan', 'Setting DemTools DKAN site name.');
  variable_set('site_name', 'DKAN | English');

  watchdog('demtools_dkan', 'Using DemTools DKAN Theme.');
  theme_disable(array('nuboot_radix'));
  theme_enable(array('demtools_dkan'));
  variable_set('admin_theme', 'demtools_dkan');
  variable_set('theme_default', 'demtools_dkan');

  watchdog('demtools_dkan', 'Reverting DemTools DKAN custom Features.');
  $features = demtools_get_features('demtools_dkan');
  demtools_revert_features($features);

  watchdog('demtools_dkan', 'Flushing all caches.');
  drupal_flush_all_caches();
}
